### PR TITLE
refactor(story-selector): hide story tags, fix selector styles

### LINKED ISSUE #431: Story selector: design updates
- [x] keep all tiles at the same height
- [x] sort filtered tags first
- [x] hide additional tags and show on click
- [x] maybe shorten too long tags with an elipsis an show full tag name on hover
- [x] Somehow the font sizes, tile sizes, spacings look different in the live app than in figma (is this the font issue?)

Also check out figma.

### PR DESCRIPTION
**Pull request by KatvonRivia**
closes #431

### CODE REVIEW

File: src/scripts/components/stories/story-tags/story-tags.tsx [hunk 1]
```diff
@@ -14,30 +14,57 @@ interface Props {
...
-
     dispatch(setSelectedStoryTags(newTags));
   };
   const getTagClasses = (tag: string) =>
     cx(styles.tag, selected.includes(tag) && styles.selected);
 
+  const sortedTags = tags.sort((a, b) => {
+    const isSelectedA = selected.includes(a);
+    const isSelectedB = selected.includes(b);
+    if (isSelectedA && !isSelectedB) {
```
Comment (pwambach) [inline src/scripts/components/stories/story-tags/story-tags.tsx:30]: Please add a new line before if block

File: src/scripts/components/stories/story-tags/story-tags.tsx [hunk 2]
```diff
@@ -14,30 +14,57 @@ interface Props {
...
+      return -1;
+    }
+    if (isSelectedB && !isSelectedA) {
```
Comment (pwambach) [inline src/scripts/components/stories/story-tags/story-tags.tsx:33]: same here

File: src/scripts/components/stories/story-tags/story-tags.tsx [hunk 3]
```diff
@@ -14,30 +14,57 @@ interface Props {
...
+      return 1;
+    }
+    return 0;
```
Comment (pwambach) [inline src/scripts/components/stories/story-tags/story-tags.tsx:36]: and here

**Review by pwambach — APPROVED** [review]
