### PR TITLE
fix(electron): update dependencies and offline middleware

### LINKED ISSUE #1345: fix electron build

### PR DESCRIPTION
**Pull request by andreashelms**
closes #1345

### CODE REVIEW

File: src/electron/load-action.ts [hunk 1]
```diff
@@ -1,29 +1,32 @@
...
     ? path.join(downloadsPath, pathToFile)
-    : path.join(downloadsPath, 'actions', type);
+    : path.join(downloadsPath, "actions", type);
 
   let action = null;
 
   try {
-    const content = fs.readFileSync(filePath, 'utf8');
+    const content = fs.readFileSync(filePath, "utf8");
+    //console.log("load action", content);
```
Comment (andreashelms) [inline src/electron/load-action.ts:19]:
```suggestion
```

**Comment by Immo-Be** [comment]
💪
