### PR TITLE
fix(marker-markup): decrease marker svg size

### LINKED ISSUE #1683: marker seems in the athmosphere
Image

### PR DESCRIPTION
**Pull request by andreashelms**
closes #1683

Before
image
Now
image

### CODE REVIEW

File: src/scripts/components/main/globe/marker-markup.tsx [hunk 1]
```diff
@@ -13,13 +13,19 @@ export const MarkerMarkup: FunctionComponent<Props> = ({ title }) => {
       className={styles.marker}
       data-marker={title}
       xmlns="http://www.w3.org/2000/svg"
-      width="48"
-      height="48"
-      viewBox="0 0 48 48"
+      width="32"
+      height="32"
+      viewBox="0 0 32 32"
```
Comment (Immo-Be) [inline src/scripts/components/main/globe/marker-markup.tsx:18]: This size was intentional, because they are too small on desktop. As this is mainly a mobile problem, maybe we can have different sizes for mobile and dekstop?

Comment (andreashelms) [reply src/scripts/components/main/globe/marker-markup.tsx:18]: Actually the marker is not smaller when being displayed. I changed marker size to the size of the former marker to be displayed at the correct position.

**Review by Immo-Be — APPROVED** [review]
