### PR TITLE
fix(embed-wizard): update params

### LINKED ISSUE #1820: update embed wizard
Image

@annikabock 
What feature parameters should the new embed wizard support?

### PR DESCRIPTION
**Pull request by Immo-Be**
closes #1820. 

This updates the embed wizard options to the new navigation. It also improves embed wizard logic and UX

With header enabled:
image

With header disabled:
image

### CODE REVIEW

File: src/scripts/components/main/navigation/navigation.tsx [hunk 1]
```diff
@@ -2,26 +2,32 @@ import { FunctionComponent, useState } from "react";
...
-import { useContentParams } from "../../../hooks/use-content-params";
-import useIsStoriesPath from "../../../hooks/use-is-stories-path";
-import { useScreenSize } from "../../../hooks/use-screen-size";
-import { EsaLogo } from "../icons/esa-logo";
-import { ArrowBackIcon } from "../icons/arrow-back-icon";
-import { setShowLayer } from "../../../reducers/show-layer-selector";
-import { StoryMode } from "../../../types/story-mode";
-import { LayerSelectorIcon } from "../icons/layer-selector-icon";
-import { contentSelector } from "../../../selectors/content";
+import { embedElementsSelector } from "../../../selectors/embed-elements-selector";
```
Comment (andreashelms) [inline src/scripts/components/main/navigation/navigation.tsx:30]: Please sort imports

File: src/scripts/components/main/navigation/navigation.tsx [hunk 2]
```diff
@@ -31,18 +37,26 @@ const Navigation: FunctionComponent = () => {
...
 
-  const {category} = useSelector(contentSelector)
+  const { category } = useSelector(contentSelector);
   const isStoriesPath = useIsStoriesPath();
 
   const { isNavigation } = useContentParams();
   const { isMobile } = useScreenSize();
 
   const { mode } = useContentParams();
+  const { header, logo, back_link, app_menu, layers_menu } = useSelector(
```
Comment (andreashelms) [inline src/scripts/components/main/navigation/navigation.tsx:47]: I'd prefer camel case here. Maybe add show prefix. e.g. `showHeader`

File: src/scripts/libs/create-embed-url.ts [hunk 3]
```diff
@@ -1,11 +1,34 @@
...
+    uncheckedKeys.forEach((key) => {
+      params.set(key, "false");
+    });
+  }
+
+  // Rebuild the new hash part
+  const newHash = `${hashPath}${params.toString() ? `?${params.toString()}` : ""}`;
+
+  // Construct and return full updated URL
+  return `${origin}${pathname}${newHash}`;
```
Comment (andreashelms) [inline src/scripts/libs/create-embed-url.ts:33]:
```suggestion
  return origin + pathname + newHash;
```

File: src/scripts/components/main/navigation/navigation.tsx (hunk 2 above)
Comment (Immo-Be) [reply src/scripts/components/main/navigation/navigation.tsx:47]: I would keep it this way, because they are also the params in the url where snake case seems appropriate. Also, it has already been implemented like this throughout the app.

**Comment by andreashelms** [comment]
If back arrow is hidden layers menu is moved to the left.

image

Do we need all these settings at all?
Wouldn't it be sufficient to make header, time-slider and legend hideable?

**Comment by andreashelms** [comment]
@Immo-Be Wizard is not scrollable. I can not see the options at the bottom.

image

**Comment by Immo-Be** [comment]
> Just noticed, embed wizard looks broken on mobile 😕
> 
> I know, but it was always like that. As this PR is quite big, let's merge this and create new issue, ok?

**Review by andreashelms — APPROVED** [review]
